apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  labels:
    app: goapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: go_app_container
        image: ssah6694/devops:9
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: go-service
  labels:
    app: goapp
spec:
  selector:
    app: goapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
