apiVersion: v1
kind: Service
metadata:
  name: go-service
  labels:
    app: goapp
spec:
  type: NodePort
  selector:
    app: goapp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080